version: '3'

services:
  web:
    build:
      context: .
      args:
        requirements: requirements/development.txt
    environment:
      - DJANGO_SETTINGS_MODULE=djangodocker.settings.development
    command: python /code/rindus/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
