version: '3'

services:
  web:
    build:
      context: .
      args:
        requirements: requirements/development.txt
    environment:
      - DJANGO_SETTINGS_MODULE=rindus.settings.development
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
